baseurl = "https://ianbibby.github.io"
title = "Coding Blog"
copyright = "Copyright &copy; 2017 - Ian Bibby"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Ian Bibby"
    github = "ianbibby"
    gitlab = ""
    linkedin = "ianbibby"
    facebook = ""
    twitter = ""
    instagram = "ianbibby"

[params]
    tagline = "Musing on coding and distributed systems"


