baseurl = "https://ianbibby.github.io"
title = "Coding Blog"
copyright = "Copyright &copy; 2017 - Ian Bibby"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Ian Bibby"
    github = "ianbibby"
    gitlab = ""
    linkedin = "ianbibby"
    facebook = ""
    twitter = ""
    instagram = "ianbibby"

[params]
    tagline = "Musing on coding and distributed systems"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
